name: workflows_run-test-suite

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:

  jobs_run-test-suite:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository onto runner
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3'
      
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run test suite
        run: |
          # Using the `-m` flag to run this python command
          # will add the current directory to `sys.path`.
          # python -m pytest
          PYTHONPATH=. pytest --cov=src/ --cov-report=term-missing > line-with-the-TOTAL.txt
          read -ra arr <<< grep TOTAL line-with-the-TOTAL.txt
          coverage_percentage=${arr[3]}
          badge="![badge-test-coverage](https://img.shields.io/static/v1?label=test-coverage&message=${coverage_percentage}&color=black)"
          echo ${badge}